
#define INCLUDE_EXTERNS
#include "common.h"

/**
 * @brief  This is the interrupt handler for Timer A.
 *
 * @return none
 *
 */
void TimerA_IRQHandler(void)
{
	if (PAC55XX_TIMERA->INT.BASEIF)
		{
		PAC55XX_TIMERA->INT.BASEIF = 1;
		}
	if (PAC55XX_TIMERA->INT.CCR0IF)
		{
		PAC55XX_TIMERA->INT.CCR0IF = 1;
		}
	if (PAC55XX_TIMERA->INT.CCR1IF)
		{
		PAC55XX_TIMERA->INT.CCR1IF = 1;
		}
	if (PAC55XX_TIMERA->INT.CCR2IF)
		{
		PAC55XX_TIMERA->INT.CCR2IF = 1;
		}
	if (PAC55XX_TIMERA->INT.CCR3IF)
		{
		PAC55XX_TIMERA->INT.CCR3IF = 1;
		}
	if (PAC55XX_TIMERA->INT.CCR4IF)
		{
		PAC55XX_TIMERA->INT.CCR4IF = 1;
		}
	if (PAC55XX_TIMERA->INT.CCR5IF)
		{
		PAC55XX_TIMERA->INT.CCR5IF = 1;
		}
	if (PAC55XX_TIMERA->INT.CCR6IF)
		{
		PAC55XX_TIMERA->INT.CCR6IF = 1;
		}
	if (PAC55XX_TIMERA->INT.CCR7IF)
		{
		PAC55XX_TIMERA->INT.CCR7IF = 1;
		}
}

